// <auto-generated />
namespace VisitorLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MadechangestotheModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadechangestotheModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201801300230064_Made changes to the Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
